npc:
  name: "&6&lTroque"
  texture: "eyJ0aW1lc3RhbXAiOjE0OTk2ODI1OTk0NzMsInByb2ZpbGVJZCI6ImRhNzQ2NWVkMjljYjRkZTA5MzRkOTIwMTc0NDkxMzU1IiwicHJvZmlsZU5hbWUiOiJJc2F5bGEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2UwNzUyMjYxZGZkMWUzOTU3NTJmOTk0YmE0ODhhOTQ3Y2M0YTM1NTM3ZWIxZTJhZDdjNDQ2MDgyNGZlOWQyIn19fQ=="
  signature: "dfhwW/gbbaPkG+DemUCWRB+RhVYaCbmDkVRUxY2NFpAEhQZsaKyK86M0XshXdHc1uTPDoYu04MmO5V+1Xj0aGZhK/OF3UEOXlDkbwLOq66MYA8avEuiBlcnt1sPsbT4AVw/yzFLtZKyu/NSKp0YOaDVCqjlg4ZMLc6acMGtYGbqY8+1WDw4+mc+X7gPEDlKBWC8ToDHylp84aEotdn2bro3Kl5AYFvexq6m3If/0ElqdOD4Uxne57AyVLriEhY8xQ8iBGSSJ5QN29CkiSocBWqxD9c2ZShqbx9EdkGuZcx0jtUaojtWsIZWMfHkqGDNqRieJThkEjaBqaaq43HUbRfJdKGEAVL5LyDfGz75kXlcZgW1yBjNY6r/omdNh1gNCzKqYsYFlTMq/VFfC86AtZ1m/RLJ6H7XWvvHjisdL+InQgtVuffG9qs36sY1vOFSZvSCL3FDX5/jPuiG45d9Bk0vPmuHzNbpTcIPvMNgTmr5+tdSimelQtd3OrvuFaHIjjca8wV1g2cBr7R+qcx08mtdAAn0Yv85Xv8ldWHYXKc/KpYiOvmSQoh3Wa8C+a/hib/aneiszFCFL8V70ldFRT2J3FxEZU6lTQTCC7KfMbbq59u1uV845sN6MafgnxneIQacflNyewGOpqS55AdOtwOHR7BpJkuAeinECXGoI6Fc="
  location:
    world: world
    x: 10
    y: 64
    z: 101
    yaw: 0
    pitch: 0

test: "test"
key_give_command: "crazycrates give p %rarity% %amount% %player%"
spawner_give_command": "zspawner give %player% %type%"
minelia_piece_give_command: "mitems give %player% minelia-money %amount%"
money_give_command: "eco give %player% %amount%"

# Les variables possibles à utiliser dans les messages sont:
# %rarity%: La rareté de la quête (minelia, mystery, legendary)
# %color%: La couleur de la rareté de la quête (à definir dans quests -> <rarity> -> color)
# %cost%: Le coût de la quête
# %rewards%: Les récompenses de la quête sous forme de liste (limiter à 5 récompenses par défaut)
# %amount%: La quantité de la récompense
# %translation%: La traduction de la récompense
menu:
  books:
    name: "&%color%&lQuête %rarity%"
    lore:
      - ""
      - "&7Achetez une &%color%quête aléatoire &7contre"
      - "&7des niveaux. Réalisez cette quête et"
      - "&7obtenez &%color%une récompense."
      - ""
      - "&7Coût : &%color%50 niveaux"
      - ""
      - "&7 Récompenses:"
      - "%rewards%"
      - ""
      - "&7Cliquez pour acheter &%color%une quête %rarity%"
    rewards: "&7- &%color%%amount% &7%translation%"


# Les variables possibles à utiliser dans les messages sont:
# %description%: La description de la quête (ex. Casser 1000 blocs)
# %progress%: La progression actuelle du joueur
# %objective%: L'objectif de la quête
quest_books:
  name: "&%color%&lQuête %rarity%"
  lore:
    - ""
    - "&7%description%"
    - ""
    - "&8%progress% / &%color%%objective%"
  completed:
    - ""
    - "&aQuête terminée!"
    - "&7Cliquez &apour réclamer &%color%votre récompense"

# Liste des quêtes et des récompenses disponibles
# <color> est la couleur de la rareté de la quête (utilisée pour les affichages)
# <cost> est le coût de la quête en niveaux
# Bien penser à incrementer les numéros des quêtes et récompenses si vous en ajoutez
# Les types de quêtes disponibles sont:
# - KILL: Tuer un certain nombre d'entités
# - BREAK: Casser un certain nombre de blocs
# - PLACE: Placer un certain nombre de blocs
quests:
  mystery:
    color: "a"
    cost: 50
    rewards:
      0:
        amount: 50000
        probability: 39.8
      1:
        amount: 100000
        probability: 10
      2:
        amount: 150000
        probability: 2
      3:
        amount: 1
        item: minelia_piece
        translation: "pièce Minelia"
        probability: 20
      4:
        amount: 2
        item: minelia_piece
        translation: "pièces Minelia"
        probability: 5
      5:
        amount: 3
        item: minelia_piece
        translation: "pièces Minelia"
        probability: 5
      6:
        amount: 1
        item: epic_key
        translation: "clé épique"
        probability: 0.1
      7:
        amount: 1
        item: blaze_spawner
        translation: "spawner blaze"
        probability: 0.1
    quests:
      0:
        type: KILL
        amount: 2000
        object: MONSTER
        description: "Tuez 2000 monstres"
      1:
        type: BREAK
        amount: 2000
        object: BLOCK
        description: "Cassez 2000 blocs"
      2:
        type: KILL
        amount: 500
        object: ZOMBIE
        description: "Tuez 500 zombies"
      3:
        type: KILL
        amount: 3000
        object: PLAYER
        description: "Tuez 3000 joueurs"
      4:
        type: BREAK
        amount: 3000
        object: BLOCK
        description: "Cassez 3000 blocs"
      5:
        type: BREAK
        amount: 1000
        object: STONE
        description: "Cassez 1000 blocs de pierre"
      6:
        type: KILL
        amount: 500
        object: COW
        description: "Tuez 500 vaches"
      7:
        type: BREAK
        amount: 4000
        object: BLOCK
        description: "Cassez 4000 blocs"

  legendary:
    cost: 100
    color: "6"
    rewards:
      0:
        amount: 100000
        probability: 39.8
      1:
        amount: 200000
        probability: 10
      2:
        amount: 300000
        probability: 2
      3:
        amount: 1
        item: minelia_piece
        translation: "pièce Minelia"
        probability: 20
      4:
        amount: 3
        item: minelia_piece
        translation: "pièces Minelia"
        probability: 5
      5:
        amount: 5
        item: minelia_piece
        translation: "pièces Minelia"
        probability: 3
      6:
        amount: 1
        item: rare_key
        translation: "clé rare"
        probability: 0.1
      7:
        amount: 1
        item: zombie_spawner
        translation: "spawner zombie"
        probability: 0.1
    quests:
      0:
        type: PLACE
        amount: 4000
        object: BLOCK
        description: "Placez 4000 blocs"
      1:
        type: BREAK
        amount: 400
        object: ORES
        description: "Cassez 400 minerais"
      2:
        type: KILL
        amount: 5000
        object: MONSTER
        description: "Tuez 5000 monstres"
      3:
        type: BREAK
        amount: 8000
        object: BLOCK
        description: "Cassez 8000 blocs"
      4:
        type: KILL
        amount: 10000
        object: PLAYER
        description: "Tuez 10000 joueurs"
      5:
        type: KILL
        amount: 1000
        object: ZOMBIE
        description: "Tuez 1000 zombies"
      6:
        type: KILL
        amount: 1000
        object: SKELETON
        description: "Tuez 1000 squelettes"
      7:
        type: BREAK
        amount: 5000
        object: BLOCK
        description: "Cassez 5000 blocs"
      8:
        type: BREAK
        amount: 8000
        object: BLOCK
        description: "Cassez 8000 blocs"
      9:
        type: PLACE
        amount: 5000
        object: BLOCK
        description: "Placez 5000 blocs"

  minelia:
    cost: 150
    color: "5"
    rewards:
      0:
        amount: 200000
        probability: 39.2
      1:
        amount: 400000
        probability: 10
      2:
        amount: 600000
        probability: 2
      3:
        amount: 3
        item: minelia_piece
        translation: "pièces Minelia"
        probability: 20
      4:
        amount: 5
        item: minelia_piece
        translation: "pièces Minelia"
        probability: 5
      5:
        amount: 10
        item: minelia_piece
        translation: "pièces Minelia"
        probability: 3
      6:
        amount: 1
        item: legendary_key
        translation: "clé légendaire"
        probability: 0.1
      7:
        amount: 1
        item: golem_spawner
        translation: "spawner à golem"
        probability: 0.1
    quests:
      0:
        type: PLACE
        amount: 2000
        object: BLOCK
        description: "Placez 2000 blocs"
      1:
        type: BREAK
        amount: 20000
        object: BLOCK
        description: "Cassez 20000 blocs"
      2:
        type: KILL
        amount: 10000
        object: MONSTER
        description: "Tuez 10000 monstres"
      3:
        type: KILL
        amount: 20000
        object: PLAYER
        description: "Tuez 20000 joueurs"
      4:
        type: BREAK
        amount: 10000
        object: BLOCK
        description: "Cassez 10000 blocs"
      5:
        type: BREAK
        amount: 5000
        object: ORES
        description: "Cassez 5000 minerais"
      6:
        type: KILL
        amount: 3000
        object: ZOMBIE
        description: "Tuez 3000 zombies"
      7:
        type: BREAK
        amount: 2000
        object: VINE
        description: "Cassez 2000 lianes"
      8:
        type: PLACE
        amount: 5000
        object: BLOCK
        description: "Placez 5000 blocs"
      9:
        type: KILL
        amount: 4000
        object: SPIDER
        description: "Tuez 4000 araignées"